const { v4: uuidv4 } = require("uuid");
const now = Date.now();

//  Users
const users = [
  "Light",
  "Alex",
  "Alice",
  "Bob",
  "Charlie",
  "Diana",
  "Ethan",
  "Fiona",
  "George",
  "Hannah",
].map((name, i) => ({
  id: uuidv4(),
  name,
  avatar: `/assets/${name.toLowerCase()}.png`,
  email: `${name.toLowerCase()}@example.com`,
  createdAt: new Date(now - (10000000 - i * 10000)).toISOString(),
  updatedAt: new Date(now - (10000000 - i * 10000)).toISOString(),
}));

const getUserIdByName = (n) => users.find((u) => u.name === n)?.id;

//  Direct Channels (exactly two participants)
const directChannels = [
   { a: "Alex", b: "Light", avatar: "avatar1.png" },
  { a: "Alice", b: "Light", avatar: "avatar2.png" },
  { a: "Bob", b: "Light", avatar: "avatar3.png" },
  { a: "Hannah", b: "Light", avatar: "avatar4.png" },
  { a: "Diana", b: "Fiona", avatar: "avatar5.png" },
  { a: "Light", b: "George", avatar: "avatar6.png" },
  { a: "Ethan", b: "Light", avatar: "avatar7.png" },
  { a: "Charlie", b: "Light", avatar: "avatar8.png" },
].map((pair) => ({
  id: uuidv4(),
  type: "direct",
  avatar: `/assets/${pair.avatar}`, 
  participants: [getUserIdByName(pair.a), getUserIdByName(pair.b)],
}));

//  Group Channels
const groupChannels = [
  {
    id: uuidv4(),
    type: "group",
    name: "Dev Team",
    avatar: "/assets/avatar9.png",
    participants: [
      getUserIdByName("Light"),
      getUserIdByName("Alice"),
      getUserIdByName("Charlie"),
      getUserIdByName("Ethan"),
      getUserIdByName("George"),
    ],
    admins: [getUserIdByName("Light")],
  },
  {
    id: uuidv4(),
    type: "group",
    name: "Casual Chat",
    avatar: "/assets/avatar10.png",
    participants: [
      getUserIdByName("Alex"),
      getUserIdByName("Light"),
      getUserIdByName("Bob"),
      getUserIdByName("Diana"),
      getUserIdByName("Fiona"),
      getUserIdByName("Hannah"),
    ],
    admins: [getUserIdByName("Alex"), getUserIdByName("Light")],
  },
];

//  Messages
const messages = [
  {
    id: uuidv4(),
    clientMessageId: "cmsg-1",
    channelId: directChannels[0].id,
    sessionId: "sess-1",
    senderId: getUserIdByName("Alex"),
    senderName: "Alex",
    senderAvatar: "/assets/avatar1.png",
    receiverId: getUserIdByName("Light"),
    receiverName: "Light",
    messageType: "text",
    content: "Hey Lightieee! How are you?",
    attachments: [],
    metadata: { reactions: [] },
    status: "sent",
    deliveryStatus: "sent",
    createdAt: new Date(now - 600000).toISOString(),
    updatedAt: new Date(now - 600000).toISOString(),
  },
  {
    id: uuidv4(),
    clientMessageId: "cmsg-2",
    channelId: directChannels[1].id,
    sessionId: "sess-1",
    senderId: getUserIdByName("Alice"),
    senderName: "Alice",
    senderAvatar: "/assets/avatar2.png",
    receiverId: getUserIdByName("Light"),
    receiverName: "Light",
    messageType: "text",
    content: "I had a great time yesterday, thanks! 😊",
    attachments: [],
    metadata: { reactions: [] },
    status: "sent",
    deliveryStatus: "delivered",
    createdAt: new Date(now - 590000).toISOString(),
    updatedAt: new Date(now - 590000).toISOString(),
  },

  {
    id: uuidv4(),
    clientMessageId: "cmsg-3",
    channelId: directChannels[2].id,
    sessionId: "sess-2",
    senderId: getUserIdByName("Light"),
    senderName: "Light",
    senderAvatar: "/assets/avatar3.png",
    receiverId: getUserIdByName("Bob"),
    receiverName: "Bob",
    messageType: "text",
    content: "Hey Bob! Are we on schedule?",
    attachments: [],
    metadata: { reactions: [] },
    status: "sent",
    deliveryStatus: "sent",
    createdAt: new Date(now - 580000).toISOString(),
    updatedAt: new Date(now - 580000).toISOString(),
  },
  {
    id: uuidv4(),
    clientMessageId: "cmsg-4",
    channelId: directChannels[3].id,
    sessionId: "sess-2",
    senderId: getUserIdByName("Hannah"),
    senderName: "Hannah",
    senderAvatar: "/assets/avatar4.png",
    receiverId: getUserIdByName("Light"),
    receiverName: "Light",
    messageType: "emoji",
    content: "👍",
    attachments: [],
    metadata: { reactions: [] },
    status: "sent",
    deliveryStatus: "read",
    createdAt: new Date(now - 570000).toISOString(),
    updatedAt: new Date(now - 570000).toISOString(),
  },

  //  Group Messages for Dev Team
  {
    id: uuidv4(),
    clientMessageId: "cmsg-5",
    channelId: groupChannels[0].id,
    sessionId: "sess-3",
    senderId: getUserIdByName("Light"),
    senderName: "Light",
    senderAvatar: "/assets/avatar1.png",
    receiverId: null,
    receiverName: null,
    messageType: "text",
    content: "Hello! everyone",
    attachments: [],
    metadata: { reactions: [] },
    status: "sent",
    deliveryStatus: "sent",
    createdAt: new Date(now - 560000).toISOString(),
    updatedAt: new Date(now - 560000).toISOString(),
  },
  {
    id: uuidv4(),
    clientMessageId: "cmsg-6",
    channelId: groupChannels[0].id,
    sessionId: "sess-3",
    senderId: getUserIdByName("George"),
    senderName: "George",
    senderAvatar: "/assets/avatar3.png",
    receiverId: null,
    receiverName: null,
    messageType: "text",
    content: "Thanks Alice!",
    attachments: [],
    metadata: { reactions: [] },
    status: "sent",
    deliveryStatus: "delivered",
    createdAt: new Date(now - 550000).toISOString(),
    updatedAt: new Date(now - 550000).toISOString(),
  },

  //  Group Messages for Casual Chat
  {
    id: uuidv4(),
    clientMessageId: "cmsg-7",
    channelId: groupChannels[1].id,
    sessionId: "sess-4",
    senderId: getUserIdByName("Bob"),
    senderName: "Bob",
    senderAvatar: "/assets/avatar2.png",
    receiverId: null,
    receiverName: null,
    messageType: "text",
    content: "Anyone up for a game tonight?",
    attachments: [],
    metadata: { reactions: [] },
    status: "sent",
    deliveryStatus: "read",
    createdAt: new Date(now - 540000).toISOString(),
    updatedAt: new Date(now - 540000).toISOString(),
  },
  {
    id: uuidv4(),
    clientMessageId: "cmsg-8",
    channelId: groupChannels[1].id,
    sessionId: "sess-4",
    senderId: getUserIdByName("Diana"),
    senderName: "Diana",
    senderAvatar: "/assets/avatar5.png",
    receiverId: null,
    receiverName: null,
    messageType: "emoji",
    content: "🎮",
    attachments: [],
    metadata: { reactions: [] },
    status: "sent",
    deliveryStatus: "delivered",
    createdAt: new Date(now - 530000).toISOString(),
    updatedAt: new Date(now - 530000).toISOString(),
  },
];
module.exports = { users, directChannels, groupChannels, messages };
